/* Version 2.3 — Protected Auto Save Conversion Master / Stock Movement Dropdown */
(()=>{
  let conversionUnlocked=false,newConvDraft=false,saveTimers=new WeakMap();
  const PASS_HASH='28995a2c0d04b66d5c7c818536bb00cd1fc1ac422aea47627de0999782fee3f4';
  async function sha256Text(text){if(window.crypto?.subtle){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}return''}
  function setConvMessage(text,type=''){const el=$('#convEditorMessage');if(!el)return;el.textContent=text||'';el.className='custom-message'+(type?' '+type:'')}
  function showConversionLogin(){return new Promise(resolve=>{const wrap=document.createElement('div');wrap.className='conv-lock-backdrop';wrap.innerHTML='<div class="conv-lock-box" role="dialog" aria-modal="true"><h3>🔐 Unit Conversion</h3><p>กรอกรหัสเพื่อเข้าใช้งาน</p><input id="convPassInput" type="password" inputmode="numeric" autocomplete="off" aria-label="รหัสเข้าใช้งาน"><div class="conv-lock-error" id="convPassError"></div><div class="conv-lock-actions"><button class="btn alt" type="button" id="convCancel">ยกเลิก</button><button class="btn" type="button" id="convEnter">เข้าใช้งาน</button></div></div>';document.body.appendChild(wrap);const inp=wrap.querySelector('#convPassInput'),err=wrap.querySelector('#convPassError'),close=v=>{wrap.remove();resolve(v)},submit=async()=>{if(await sha256Text(inp.value)===PASS_HASH)close(true);else{err.textContent='รหัสไม่ถูกต้อง';inp.value='';inp.focus()}};wrap.querySelector('#convCancel').onclick=()=>close(false);wrap.querySelector('#convEnter').onclick=submit;inp.onkeydown=e=>{if(e.key==='Enter')submit();if(e.key==='Escape')close(false)};wrap.onclick=e=>{if(e.target===wrap)close(false)};setTimeout(()=>inp.focus(),30)})}
  function openPage(tab){$$('.tab').forEach(x=>x.classList.remove('active'));$$('.page').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$('#conversion').classList.add('active');renderConv()}
  const convTab=$('.tab[data-p="conversion"]');if(convTab)convTab.onclick=async()=>{conversionUnlocked=false;if(!await showConversionLogin())return;conversionUnlocked=true;openPage(convTab)};$$('.tab').filter(t=>t.dataset.p!=='conversion').forEach(t=>t.addEventListener('click',()=>conversionUnlocked=false));

  function stockMaster(){const m=new Map();for(const r of S.stock||[]){const code=T(V(r,'rm'));if(!code)continue;const desc=T(V(r,'rmd')),unit=T(V(r,'stocku'))||T(V(r,'stockuc'));if(!m.has(code))m.set(code,{code,desc,unit});else{const x=m.get(code);if(!x.desc&&desc)x.desc=desc;if(!x.unit&&unit)x.unit=unit}}return[...m.values()].sort((a,b)=>a.code.localeCompare(b.code,'en',{numeric:true}))}
  function masterRows(){const map=new Map();for(const r of S.convert||[]){if(r?.code)map.set(T(r.code),{source:'master',code:T(r.code),desc:T(r.desc),unit:T(r.unit),factor:N(r.factor),convertUnit:T(r.convertUnit)})}for(const n of S.needs||[]){if(n?.rm&&!map.has(T(n.rm)))map.set(T(n.rm),{source:'need',code:T(n.rm),desc:T(n.desc),unit:T(n.su),factor:0,convertUnit:T(n.bu)})}return[...map.values()].sort((a,b)=>a.code.localeCompare(b.code,'en',{numeric:true}))}
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
  function productBlock(r){return `<div class="conv-product"><div class="conv-product-code">${esc(r.code)}</div><div class="conv-product-name">${esc(r.desc||'-')}</div><span class="conv-source ${r.source==='need'?'need':''}">${r.source==='need'?'Need Conversion':'Convert Master'}</span></div>`}
  function field(label,field,value,opts={}){const type=opts.number?'number':'text',ro=opts.readonly?'readonly':'',extra=opts.number?'step="any" min="0"':'';return `<div class="conv-field"><label>${label}</label><input data-field="${field}" type="${type}" ${extra} ${ro} value="${esc(value)}"></div>`}
  function rowHtml(r){return `<div class="conv-card" data-code="${esc(r.code)}" data-source="${r.source}">${productBlock(r)}${field('หน่วยใหญ่','unit',r.unit)}<div class="conv-arrow-big">→</div>${field('จำนวนหน่วยย่อย','factor',r.factor||'',{number:true})}${field('หน่วยย่อย','convertUnit',r.convertUnit)}<div class="conv-actions"><span class="conv-save-state saved">บันทึกแล้ว</span><button class="btn danger small conv-delete" type="button">ลบ</button></div></div>`}
  function newRowHtml(){const used=new Set((S.convert||[]).map(x=>T(x.code))),products=stockMaster().filter(x=>!used.has(x.code));const options='<option value="">-- เลือก RM จาก Stock Movement --</option>'+products.map(x=>`<option value="${esc(x.code)}">${esc(x.code)} - ${esc(x.desc||'')}</option>`).join('');return `<div class="conv-card is-new" data-source="new"><div class="conv-new-select"><div class="conv-field"><label>สินค้า / RM จาก Stock Movement</label><select data-field="product">${options}</select></div>${field('หน่วยใหญ่','unit','',{readonly:true})}<div class="conv-arrow-big">→</div>${field('จำนวนหน่วยย่อย','factor','',{number:true})}${field('หน่วยย่อย','convertUnit','')}<div class="conv-actions"><span class="conv-save-state">เลือกสินค้าแล้วกรอกหน่วยย่อย</span><button class="btn alt small conv-cancel" type="button">ยกเลิก</button></div></div></div>`}
  function setState(card,text,cls=''){const e=card.querySelector('.conv-save-state');if(!e)return;e.textContent=text;e.className='conv-save-state'+(cls?' '+cls:'')}
  async function persistExisting(card,recalc=false){const code=T(card.dataset.code),unit=T(card.querySelector('[data-field="unit"]')?.value),convertUnit=T(card.querySelector('[data-field="convertUnit"]')?.value),factor=N(card.querySelector('[data-field="factor"]')?.value);if(!code||!unit||!convertUnit||factor<=0){setState(card,'ข้อมูลยังไม่ครบ','saving');return false}let row=(S.convert||[]).find(r=>T(r.code)===code);if(!row){const src=masterRows().find(r=>r.code===code);row={code,desc:src?.desc||'',unit,factor,convertUnit};S.convert.push(row)}else{row.unit=unit;row.factor=factor;row.convertUnit=convertUnit}S.meta.convert=S.meta.convert||'Manual Conversion Master';setState(card,'กำลังบันทึก...','saving');buildIndexes();invalidateCalcCache();await save();setState(card,'บันทึกแล้ว','saved');if(recalc){compute();setConvMessage(`Auto Save ${code}: 1 ${unit} → ${F(factor)} ${convertUnit}`,'ok')}return true}
  async function persistNew(card){const code=T(card.querySelector('[data-field="product"]')?.value),unit=T(card.querySelector('[data-field="unit"]')?.value),convertUnit=T(card.querySelector('[data-field="convertUnit"]')?.value),factor=N(card.querySelector('[data-field="factor"]')?.value);if(!code||!unit||!convertUnit||factor<=0){setState(card,'กรอกข้อมูลให้ครบเพื่อ Auto Save','saving');return false}if((S.convert||[]).some(r=>T(r.code)===code)){setConvMessage(`RM Code ${code} มีใน Conversion Master แล้ว`,'warn');return false}const p=stockMaster().find(x=>x.code===code);S.convert.push({code,desc:p?.desc||'',unit,factor,convertUnit});S.meta.convert=S.meta.convert||'Manual Conversion Master';setState(card,'กำลังบันทึก...','saving');buildIndexes();invalidateCalcCache();await save();newConvDraft=false;compute();renderConv();setConvMessage(`เพิ่ม ${code} จาก Stock Movement และ Auto Save แล้ว`,'ok');return true}
  function schedule(card,recalc=false){clearTimeout(saveTimers.get(card));setState(card,'กำลังรอบันทึก...','saving');const t=setTimeout(()=>card.dataset.source==='new'?persistNew(card):persistExisting(card,recalc),650);saveTimers.set(card,t)}
  async function deleteRow(card){const code=T(card.dataset.code);if(!code||!confirm(`ลบ Conversion ของ ${code} หรือไม่?`))return;S.convert=(S.convert||[]).filter(r=>T(r.code)!==code);for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k?.startsWith('conv:'+code+':'))localStorage.removeItem(k)}buildIndexes();invalidateCalcCache();await save();compute();renderConv();setConvMessage(`ลบ ${code} แล้ว`,'warn')}

  renderConv=function(){const list=$('#convList');if(!list)return;const q=K($('#convSearch')?.value||''),all=masterRows(),show=all.filter(r=>!q||K([r.code,r.desc,r.unit,r.convertUnit].join(' ')).includes(q));list.innerHTML=(newConvDraft?newRowHtml():'')+(show.length?show.map(rowHtml).join(''):'<div class="conv-empty">ไม่พบรายการ Conversion</div>');const count=$('#convMasterCount');if(count)count.textContent=`${all.length.toLocaleString()} รายการ${show.length!==all.length?` • แสดง ${show.length.toLocaleString()}`:''}`;
    list.querySelectorAll('.conv-card[data-source="master"],.conv-card[data-source="need"]').forEach(card=>{card.querySelectorAll('input').forEach(inp=>{inp.addEventListener('input',()=>schedule(card,false));inp.addEventListener('change',()=>schedule(card,true))});card.querySelector('.conv-delete')?.addEventListener('click',()=>deleteRow(card))});
    const draft=list.querySelector('.conv-card[data-source="new"]');if(draft){const sel=draft.querySelector('[data-field="product"]');sel?.addEventListener('change',()=>{const p=stockMaster().find(x=>x.code===T(sel.value));draft.querySelector('[data-field="unit"]').value=p?.unit||'';setState(draft,p?`เลือก ${p.code} แล้ว • กรอกจำนวนและหน่วยย่อย`:'เลือกสินค้าเพื่อเริ่มต้น',p?'saving':'');schedule(draft,false)});draft.querySelectorAll('input').forEach(inp=>{inp.addEventListener('input',()=>schedule(draft,false));inp.addEventListener('change',()=>schedule(draft,true))});draft.querySelector('.conv-cancel')?.addEventListener('click',()=>{newConvDraft=false;renderConv()})}
  };
  const search=$('#convSearch');if(search)search.oninput=renderConv;const add=$('#addConvRow');if(add)add.onclick=()=>{if(!S.stock?.length){setConvMessage('กรุณา Upload Stock Movement ก่อนเพิ่มสินค้าใหม่','warn');return}newConvDraft=true;renderConv();setTimeout(()=>$('#convList [data-source="new"] select')?.focus(),0)};
  const ver=document.querySelector('.version');if(ver)ver.textContent='Version 2.3 • Auto Save Conversion Master';renderConv();
})();
