const S={stock:[],item:[],recipe:[],wip:[],analysis:[],needs:[],recon:[],stockDate:'',meta:{},currentExpected:new Map()};
const IDX={recipeByRec:new Map(),wipByCode:new Map(),stockByBranch:new Map(),salesAll:new Map(),salesByDate:new Map(),recipeCodes:new Set(),expectedCache:new Map(),wipUnitCache:new Map()};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const T=v=>String(v??'').trim();
const N=v=>{let n=Number(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:0};
const K=v=>T(v).toLowerCase().replace(/\s+/g,'').replace(/[.\-_\/()]/g,'');
const F=n=>Number.isFinite(n)?n.toLocaleString('th-TH',{maximumFractionDigits:3}):'';
const alias={wh:['warehousecode','shopcode'],whn:['warehousename','shopname'],rm:['rmcode'],rmd:['rmdescription'],date:['dateperiod','deliverydate'],stocku:['stockunitname'],stockuc:['stockunitcode'],bf:['bf'],gr:['gr'],tin:['tin'],wipin:['wipin'],adjin:['adjin'],rtv:['rtv'],tout:['tout'],wipout:['wipout'],damage:['damage'],adjout:['adjout'],sales:['salesusage'],waste:['wasteusage'],theory:['theorystock'],actual:['actualstock'],cost:['stdcostunit'],item:['itemcode'],itemd:['description1'],qty:['totalqty'],rec:['reccode'],comp:['itemcode'],compq:['quantity'],unit:['unitdes1'],mod:['modifdate','modifydate'],wipc:['wipcode'],fgq:['fgqty'],rmitem:['rmitemcode'],rmq:['rmqty'],rmu:['rmunit']};
function V(r,n){for(const a of alias[n]||[])for(const k of Object.keys(r||{}))if(K(k)===a)return r[k];return''}
let DBP=null;
function openDB(){if(DBP)return DBP;DBP=new Promise((resolve,reject)=>{const req=indexedDB.open('kamu_inventory_audit_db',1);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('datasets'))d.createObjectStore('datasets')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return DBP}
async function dbPut(k,v){const d=await openDB();return new Promise((resolve,reject)=>{const tx=d.transaction('datasets','readwrite');tx.objectStore('datasets').put(v,k);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
async function dbGet(k){const d=await openDB();return new Promise((resolve,reject)=>{const req=d.transaction('datasets','readonly').objectStore('datasets').get(k);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function save(){await dbPut('state',{stock:S.stock,item:S.item,recipe:S.recipe,wip:S.wip,stockDate:S.stockDate,meta:S.meta})}
async function load(){try{const x=await dbGet('state');if(x){Object.assign(S,x);return}const legacy=JSON.parse(localStorage.getItem('kamu_inv_stock')||'null');if(legacy&&typeof legacy==='object'){Object.assign(S,legacy);await save();localStorage.removeItem('kamu_inv_stock')}}catch(e){console.warn('Database load warning',e);try{localStorage.removeItem('kamu_inv_stock')}catch{}}}
let customChecks={},activeCustomCheck='',customDirty=false;
async function loadCustomChecks(){try{const saved=await dbGet('customChecks');customChecks=saved&&typeof saved==='object'&&!Array.isArray(saved)?saved:{};const last=localStorage.getItem('inventory:lastCustomCheck')||'';if(last&&customChecks[last])activeCustomCheck=last}catch(e){console.warn('Custom Check load warning',e);customChecks={}}}
async function persistCustomChecks(){await dbPut('customChecks',customChecks)}
function customCheckNames(){return Object.keys(customChecks).sort((a,b)=>a.localeCompare(b,'th',{numeric:true}))}
function setCustomMessage(text,type=''){const el=$('#customCheckMessage');if(!el)return;el.textContent=text||'';el.className='custom-message'+(type?' '+type:'')}
function renderCustomChecks(){const sel=$('#customCheckSelect');if(!sel)return;const keep=activeCustomCheck&&customChecks[activeCustomCheck]?activeCustomCheck:'';sel.innerHTML='<option value="">-- เลือกชุด Custom Check --</option>'+customCheckNames().map(n=>`<option value="${n.replaceAll('"','&quot;')}">${n} (${(customChecks[n]||[]).length})</option>`).join('');if(keep)sel.value=keep;const valid=new Set(rmChoices().map(x=>x.code)),total=keep?(customChecks[keep]||[]).length:0,available=keep?(customChecks[keep]||[]).filter(x=>valid.has(x)).length:0;const meta=$('#customCheckMeta');if(meta)meta.textContent=keep?`${keep} • ใช้ได้ ${available}/${total} รายการ${customDirty?' • มีการแก้ไข ยังไม่ได้บันทึกทับ':''}`:`บันทึกชุดรายการตรวจไว้ใช้ครั้งถัดไป`;const u=$('#updateCustom'),d=$('#deleteCustom');if(u)u.disabled=!keep;if(d)d.disabled=!keep}
function syncActiveCustomCheck(analysis=S.analysis){if(!activeCustomCheck||!customChecks[activeCustomCheck])return;const valid=new Set(analysis.map(x=>x.rm));selectedRM=new Set(customChecks[activeCustomCheck].filter(x=>valid.has(x)));customDirty=false}
function applyCustomCheck(name,notify=true){if(!name||!customChecks[name]){activeCustomCheck='';customDirty=false;localStorage.removeItem('inventory:lastCustomCheck');renderCustomChecks();return}activeCustomCheck=name;customDirty=false;localStorage.setItem('inventory:lastCustomCheck',name);const valid=new Set(rmChoices().map(x=>x.code));selectedRM=new Set((customChecks[name]||[]).filter(x=>valid.has(x)));renderRMFilter(true);render();renderCustomChecks();if(notify)setCustomMessage(`ใช้ชุด “${name}” แล้ว • ${selectedRM.size} รายการ`,'ok')}
function markCustomDirty(){if(activeCustomCheck){customDirty=true;renderCustomChecks()}}
async function saveCustomCheckAs(){if(!selectedRM.size){alert('กรุณาเลือก RM อย่างน้อย 1 รายการก่อนบันทึก Custom Check');return}let name=prompt('ตั้งชื่อชุด Custom Check เช่น Daily Check / High Value / Milk & Tea');if(name===null)return;name=T(name);if(!name)return;if(customChecks[name]&&!confirm(`มีชุด “${name}” อยู่แล้ว ต้องการบันทึกทับหรือไม่?`))return;customChecks[name]=[...selectedRM].sort((a,b)=>a.localeCompare(b,'en',{numeric:true}));activeCustomCheck=name;customDirty=false;localStorage.setItem('inventory:lastCustomCheck',name);await persistCustomChecks();renderCustomChecks();setCustomMessage(`บันทึกชุด “${name}” แล้ว • ${selectedRM.size} รายการ`,'ok')}
async function updateCustomCheck(){if(!activeCustomCheck||!customChecks[activeCustomCheck])return;if(!selectedRM.size){alert('Custom Check ต้องมีอย่างน้อย 1 รายการ');return}customChecks[activeCustomCheck]=[...selectedRM].sort((a,b)=>a.localeCompare(b,'en',{numeric:true}));customDirty=false;await persistCustomChecks();renderCustomChecks();setCustomMessage(`บันทึกทับชุด “${activeCustomCheck}” แล้ว`,'ok')}
async function deleteCustomCheck(){if(!activeCustomCheck||!customChecks[activeCustomCheck])return;const name=activeCustomCheck;if(!confirm(`ลบชุด Custom Check “${name}” หรือไม่?`))return;delete customChecks[name];activeCustomCheck='';customDirty=false;localStorage.removeItem('inventory:lastCustomCheck');await persistCustomChecks();renderCustomChecks();setCustomMessage(`ลบชุด “${name}” แล้ว`,'warn')}
function findHeader(a,type){let sig={stock:['warehousecode','rmcode'],item:['shopcode','itemcode','totalqty'],recipe:['reccode','itemcode','quantity'],wip:['wipcode','fgqty','rmqty']}[type];for(let i=0;i<Math.min(80,a.length);i++){let s=new Set((a[i]||[]).map(K));if(sig.every(x=>s.has(x)))return i}return-1}
function rows(ws,type){let a=XLSX.utils.sheet_to_json(ws,{header:1,defval:''}),h=findHeader(a,type);if(h<0)throw Error('ไม่พบ Header '+type);let out=XLSX.utils.sheet_to_json(ws,{range:h,defval:''}).filter(r=>Object.values(r).some(x=>T(x)));return out.filter(r=>{if(type==='stock'){let wh=T(V(r,'wh')),rm=T(V(r,'rm'));return wh&&rm&&wh!=='รหัสคลังสินค้า'&&rm!=='รหัสวัตถุดิบ'}if(type==='item'){let wh=T(V(r,'wh')),it=T(V(r,'item'));return wh&&it&&wh!=='รหัสสาขา'&&it!=='รหัสสินค้า'}if(type==='recipe')return T(V(r,'rec'))&&T(V(r,'comp'));if(type==='wip')return T(V(r,'wipc'))&&T(V(r,'rmitem'));return true})}
function reportDate(wb,ws){let a=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});for(let r=0;r<Math.min(15,a.length);r++)for(let c=0;c<(a[r]||[]).length;c++){let s=T(a[r][c]);let m=s.match(/(\d{1,2}[\/-]\d{1,2}[\/-]\d{4})/);if(m)return m[1]}let m=(wb.SheetNames[0]||'').match(/(\d{4}-\d{2}-\d{2})/);return m?m[1]:''}
function addQty(map,key,qty){map.set(key,(map.get(key)||0)+qty)}
function buildIndexes(){IDX.recipeByRec=new Map();IDX.wipByCode=new Map();IDX.stockByBranch=new Map();IDX.salesAll=new Map();IDX.salesByDate=new Map();IDX.recipeCodes=new Set();IDX.expectedCache=new Map();IDX.wipUnitCache=new Map();for(const r of S.recipe){const rec=T(V(r,'rec'));if(!rec)continue;IDX.recipeCodes.add(rec);if(!IDX.recipeByRec.has(rec))IDX.recipeByRec.set(rec,[]);IDX.recipeByRec.get(rec).push(r)}for(const r of S.wip){const code=T(V(r,'wipc'));if(!code)continue;if(!IDX.wipByCode.has(code))IDX.wipByCode.set(code,[]);IDX.wipByCode.get(code).push(r)}for(const r of S.stock){const b=T(V(r,'wh'));if(!b)continue;if(!IDX.stockByBranch.has(b))IDX.stockByBranch.set(b,[]);IDX.stockByBranch.get(b).push(r)}for(const r of S.item){const b=T(V(r,'wh')),d=T(V(r,'date')),item=T(V(r,'item')),qty=N(V(r,'qty'));if(!b||!item||!qty)continue;if(!IDX.salesAll.has(b))IDX.salesAll.set(b,new Map());addQty(IDX.salesAll.get(b),item,qty);const kd=b+'\u0001'+d;if(!IDX.salesByDate.has(kd))IDX.salesByDate.set(kd,new Map());addQty(IDX.salesByDate.get(kd),item,qty)}}
function invalidateCalcCache(){IDX.expectedCache.clear();IDX.wipUnitCache.clear()}