const exportCols=[
 ['RM',x=>x.rm],['Description',x=>x.desc],['Unit',x=>x.unit],['T.Out',x=>x.tout],['WIP Out',x=>x.wipout],['Damage',x=>x.damage],['Adj.Out',x=>x.adjout],
 ['BOM Raw Usage',x=>x.bomRaw],['BOM Stock Usage',x=>x.bom??''],['Movement Sales Usage',x=>x.mov],['Usage Var',x=>x.uv??''],['Waste',x=>x.waste],
 ['Calc Theory',x=>x.calc??''],['Report Theory',x=>x.reportTheory],['Report Actual',x=>x.reportActual],['Actual Count',x=>x.count??''],['Count Diff',x=>x.diff??''],['Diff %',x=>x.diffp??''],['Std.Cost',x=>x.cost],['Variance Cost',x=>x.vc],['Status',x=>x.status]
];
function exportFileBase(){const b=$('#branch').value||'ALL',d=$('#date').value||'ALL_DATE',cc=activeCustomCheck?'-'+activeCustomCheck.replace(/[^a-zA-Z0-9ก-๙_-]+/g,'_'):'';return `KAMU_Inventory_${b}_${d}${cc}`}
function exportRows(){return filteredAnalysis().map(x=>exportCols.map(([,get])=>get(x)))}
function exportMeta(){const b=$('#branch'),branchText=b?.selectedOptions?.[0]?.textContent||b?.value||'-';return {branch:branchText,date:$('#date').value||'ทั้งหมด',custom:activeCustomCheck||'ไม่ใช้',status:$('#status').value||'ทั้งหมด',rows:filteredAnalysis().length}}
function escCsv(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function downloadCsv(){const lines=[exportCols.map(x=>x[0]).join(',')].concat(exportRows().map(r=>r.map(escCsv).join(','))),el=document.createElement('a');el.href=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}));el.download=exportFileBase()+'.csv';el.click();URL.revokeObjectURL(el.href)}
function exportExcelFile(){if(!window.XLSX){alert('ตัวสร้าง Excel ยังโหลดไม่สำเร็จ กรุณา Refresh แล้วลองใหม่');return}const meta=exportMeta(),rows=exportRows(),aoa=[['KAMU Inventory Stock Checker'],['Branch',meta.branch],['Item Sale Date',meta.date],['Custom Check',meta.custom],['Status',meta.status],['Exported Rows',meta.rows],[],exportCols.map(x=>x[0]),...rows];const ws=XLSX.utils.aoa_to_sheet(aoa);ws['!cols']=exportCols.map((c,i)=>({wch:i===1?34:i===0?14:16}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Inventory Audit');XLSX.writeFile(wb,exportFileBase()+'.xlsx')}
function loadScriptOnce(src,test){return new Promise((resolve,reject)=>{if(test())return resolve();const old=[...document.scripts].find(x=>x.src===src);if(old){if(test())resolve();else{old.addEventListener('load',resolve,{once:true});old.addEventListener('error',()=>reject(Error('โหลด Library ไม่สำเร็จ')),{once:true})}return}const sc=document.createElement('script');sc.src=src;sc.onload=resolve;sc.onerror=()=>reject(Error('โหลด Library ไม่สำเร็จ'));document.head.appendChild(sc)})}
async function ensureCanvas(){await loadScriptOnce('https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js',()=>!!window.html2canvas)}
async function ensurePdf(){await ensureCanvas();await loadScriptOnce('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.umd.min.js',()=>!!window.jspdf)}
async function ensurePpt(){await ensureCanvas();await loadScriptOnce('https://cdn.jsdelivr.net/npm/pptxgenjs@3.12.0/dist/pptxgen.bundle.js',()=>!!window.PptxGenJS)}
function makeExportPages(){const data=filteredAnalysis(),meta=exportMeta(),per=22,total=Math.max(1,Math.ceil(data.length/per)),pages=[];const compact=[['RM',x=>x.rm],['Description',x=>x.desc],['Unit',x=>x.unit],['BOM Stock',x=>x.bom==null?'—':F(x.bom)],['Sales Usage',x=>F(x.mov)],['Actual Count',x=>x.count??''],['Count Diff',x=>x.diff==null?'':F(x.diff)],['Diff %',x=>x.diffp==null?'':F(x.diffp)+'%'],['Variance Cost',x=>F(x.vc)],['Status',x=>x.status]];for(let p=0;p<total;p++){const part=data.slice(p*per,(p+1)*per),box=document.createElement('div');box.style.cssText='position:fixed;left:-100000px;top:0;width:1400px;padding:34px;background:#fff;color:#173a28;font-family:Arial,"Noto Sans Thai",sans-serif;box-sizing:border-box';box.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:flex-start;border-bottom:4px solid #238a55;padding-bottom:15px;margin-bottom:16px"><div><div style="font-size:28px;font-weight:800">KAMU Inventory Stock Checker</div><div style="font-size:16px;margin-top:5px">Inventory Audit Report</div></div><div style="text-align:right;font-size:14px">Page ${p+1}/${total}<br>${new Date().toLocaleString('th-TH')}</div></div><div style="display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:10px;font-size:14px;margin-bottom:16px"><div><b>Branch:</b> ${meta.branch}</div><div><b>Date:</b> ${meta.date}</div><div><b>Custom:</b> ${meta.custom}</div><div><b>Status:</b> ${meta.status}</div></div><table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr>${compact.map(c=>`<th style="background:#dff4e7;border:1px solid #abd5ba;padding:7px;text-align:left">${c[0]}</th>`).join('')}</tr></thead><tbody>${part.map((x,i)=>`<tr style="background:${i%2?'#f8fcf9':'#fff'}">${compact.map(c=>`<td style="border:1px solid #d5e6dc;padding:7px">${String(c[1](x)??'')}</td>`).join('')}</tr>`).join('')}</tbody></table><div style="margin-top:14px;font-size:12px;color:#5b7767">Rows ${part.length} / Filtered total ${data.length} • Custom Check: ${meta.custom}</div>`;document.body.appendChild(box);pages.push(box)}return pages}
async function renderExportCanvases(){await ensureCanvas();const pages=makeExportPages(),canvases=[];try{for(const p of pages)canvases.push(await html2canvas(p,{scale:1.25,backgroundColor:'#ffffff',logging:false,useCORS:true}))}finally{pages.forEach(p=>p.remove())}return canvases}
async function exportPdfFile(){try{await ensurePdf();const canvases=await renderExportCanvases(),{jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});canvases.forEach((c,i)=>{if(i)pdf.addPage('a4','landscape');const img=c.toDataURL('image/jpeg',.92),pw=pdf.internal.pageSize.getWidth(),ph=pdf.internal.pageSize.getHeight(),r=Math.min(pw/c.width,ph/c.height),w=c.width*r,h=c.height*r;pdf.addImage(img,'JPEG',(pw-w)/2,(ph-h)/2,w,h)});pdf.save(exportFileBase()+'.pdf')}catch(e){alert('Export PDF ไม่สำเร็จ: '+e.message)}}
async function exportPptFile(){try{await ensurePpt();const canvases=await renderExportCanvases(),pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author='KAMU';pptx.subject='Inventory Audit';pptx.title='KAMU Inventory Stock Checker';for(const c of canvases){const slide=pptx.addSlide();slide.background={color:'FFFFFF'};slide.addImage({data:c.toDataURL('image/png'),x:0,y:0,w:13.333,h:7.5})}await pptx.writeFile({fileName:exportFileBase()+'.pptx'})}catch(e){alert('Export PowerPoint ไม่สำเร็จ: '+e.message)}}
$('#exportCsv').onclick=downloadCsv;$('#exportExcel').onclick=exportExcelFile;$('#exportPdf').onclick=exportPdfFile;$('#exportPpt').onclick=exportPptFile;
(async()=>{try{if(navigator.storage&&navigator.storage.persist)navigator.storage.persist().catch(()=>{});await load();await loadCustomChecks()}catch(e){console.warn(e)}buildIndexes();refresh();renderCustomChecks();compute()})();