(()=>{
let unlocked=false,newRow=false;const PH='28995a2c0d04b66d5c7c818536bb00cd1fc1ac422aea47627de0999782fee3f4';
async function h(t){if(!crypto?.subtle)return'';const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function msg(t,c=''){const e=$('#convEditorMessage');if(e){e.textContent=t||'';e.className='custom-message'+(c?' '+c:'')}}
function login(){return new Promise(ok=>{const w=document.createElement('div');w.className='conv-lock-backdrop';w.innerHTML='<div class="conv-lock-box"><h3>🔐 Unit Conversion</h3><p>กรอกรหัสเพื่อเข้าใช้งาน</p><input id="cp" type="password" inputmode="numeric" autocomplete="off"><div class="conv-lock-error" id="ce"></div><div class="conv-lock-actions"><button class="btn alt" id="cx" type="button">ยกเลิก</button><button class="btn" id="co" type="button">เข้าใช้งาน</button></div></div>';document.body.appendChild(w);const i=w.querySelector('#cp'),e=w.querySelector('#ce'),close=v=>{w.remove();ok(v)},go=async()=>{if(await h(i.value)===PH)close(true);else{e.textContent='รหัสไม่ถูกต้อง';i.value='';i.focus()}};w.querySelector('#cx').onclick=()=>close(false);w.querySelector('#co').onclick=go;i.onkeydown=x=>{if(x.key==='Enter')go();if(x.key==='Escape')close(false)};setTimeout(()=>i.focus(),20)})}
const tab=$('.tab[data-p="conversion"]');if(tab)tab.onclick=async()=>{unlocked=false;if(!await login())return;unlocked=true;$$('.tab').forEach(x=>x.classList.remove('active'));$$('.page').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$('#conversion').classList.add('active');renderConv()};$$('.tab').filter(x=>x.dataset.p!=='conversion').forEach(x=>x.addEventListener('click',()=>unlocked=false));
function rows(){const m=new Map();for(const r of S.convert||[])if(r?.code)m.set(T(r.code),{src:'master',orig:T(r.code),code:T(r.code),desc:T(r.desc),unit:T(r.unit),factor:N(r.factor),small:T(r.convertUnit)});for(const n of S.needs||[])if(n?.rm&&!m.has(T(n.rm)))m.set(T(n.rm),{src:'need',orig:T(n.rm),code:T(n.rm),desc:T(n.desc),unit:T(n.su),factor:0,small:T(n.bu)});return[...m.values()].sort((a,b)=>a.code.localeCompare(b.code,'en',{numeric:true}))}
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const inp=(v,c,f,n=false)=>`<input class="${c}" data-f="${f}" ${n?'type="number" step="any" min="0"':''} value="${esc(v)}">`;
function html(r,n=false){const s=n?'new':r.src;return`<tr data-o="${esc(r.orig||'')}" data-s="${s}"><td>${inp(r.code,'conv-code','code')}</td><td>${inp(r.desc,'conv-desc','desc')}</td><td>${inp(r.unit,'conv-unit','unit')}</td><td class="conv-one">1</td><td class="conv-arrow">→</td><td>${inp(r.factor||'','conv-factor','factor',true)}</td><td>${inp(r.small,'conv-unit','small')}</td><td><span class="conv-source ${s==='need'?'need':s==='new'?'new':''}">${s==='master'?'Convert Master':s==='need'?'Need Conversion':'New'}</span></td><td><div class="conv-actions"><button class="btn small cs" type="button">💾 บันทึก</button>${n?'<button class="btn alt small cc" type="button">ยกเลิก</button>':'<button class="btn danger small cd" type="button">ลบ</button>'}</div></td></tr>`}
renderConv=function(){const b=$('#convTbl tbody');if(!b)return;const q=K($('#convSearch')?.value||''),all=rows(),show=all.filter(r=>!q||K([r.code,r.desc,r.unit,r.small].join(' ')).includes(q));b.innerHTML=(newRow?html({src:'new',orig:'',code:'',desc:'',unit:'',factor:'',small:''},true):'')+show.map(r=>html(r)).join('');$('#convMasterCount').textContent=`${all.length.toLocaleString()} รายการ${show.length!==all.length?` • แสดง ${show.length.toLocaleString()}`:''}`;b.querySelectorAll('.cs').forEach(x=>x.onclick=()=>saveRow(x.closest('tr')));b.querySelectorAll('.cd').forEach(x=>x.onclick=()=>delRow(x.closest('tr')));b.querySelectorAll('.cc').forEach(x=>x.onclick=()=>{newRow=false;renderConv()})};
async function saveRow(tr){const g=f=>T(tr.querySelector(`[data-f="${f}"]`)?.value),code=g('code'),desc=g('desc'),unit=g('unit'),small=g('small'),factor=N(g('factor')),orig=T(tr.dataset.o);if(!code||!unit||!small||factor<=0){msg('กรุณากรอก RM Code, หน่วยใหญ่, จำนวนหน่วยย่อย และหน่วยย่อยให้ครบ','warn');return}if((S.convert||[]).some(r=>T(r.code)===code&&T(r.code)!==orig)){msg(`มี RM Code ${code} อยู่แล้ว`,'warn');return}const row={code,desc,unit,factor,convertUnit:small},ix=(S.convert||[]).findIndex(r=>T(r.code)===orig);if(ix>=0)S.convert[ix]=row;else S.convert.push(row);newRow=false;S.meta.convert=S.meta.convert||'Manual Conversion Master';buildIndexes();invalidateCalcCache();await save();compute();renderConv();msg(`บันทึก ${code}: 1 ${unit} → ${F(factor)} ${small} แล้ว`,'ok')}
async function delRow(tr){const code=T(tr.dataset.o);if(!code||!confirm(`ลบ Conversion ของ ${code} หรือไม่?`))return;S.convert=(S.convert||[]).filter(r=>T(r.code)!==code);for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k?.startsWith('conv:'+code+':'))localStorage.removeItem(k)}buildIndexes();invalidateCalcCache();await save();compute();renderConv();msg(`ลบ ${code} แล้ว`,'warn')}
const s=$('#convSearch');if(s)s.oninput=renderConv;const a=$('#addConvRow');if(a)a.onclick=()=>{newRow=true;renderConv();setTimeout(()=>$('#convTbl tbody tr[data-s="new"] .conv-code')?.focus(),0)};const v=document.querySelector('.version');if(v)v.textContent='Version 2.2 • Protected Conversion Master';renderConv();
})();
