(()=>{
const c=['RM','Description','Unit','B/F','GR','T.In','T.Out','WIP Out','Damage','Waste','BOM Raw Usage','BOM Stock Usage','Movement Sales Usage','Usage Var','Calc Theory','Report Theory','Actual Stock','Actual Count','Count Diff','Diff %','Std.Cost','Variance Cost','Status'];
const r0=render;
function r1(){const a=filteredAnalysis();$('#tbl thead').innerHTML='<tr>'+c.map(x=>'<th>'+x+'</th>').join('')+'</tr>';$('#tbl tbody').innerHTML=a.map(x=>`<tr><td>${x.rm}</td><td>${x.desc}</td><td>${x.unit}</td>${['bf','gr','tin','tout','wipout','damage','waste'].map(k=>`<td class="num">${F(x[k])}</td>`).join('')}<td class="bom-raw">${x.bomRaw||''}${x.missingConv?` <span class="needs-tag">ต้องแปลง ${x.missingConv}</span>`:''}</td><td class="num">${x.bom==null?'—':F(x.bom)}</td><td class="num">${F(x.mov)}</td><td class="num">${x.uv==null?'—':F(x.uv)}</td><td class="num">${x.calc==null?'—':F(x.calc)}</td><td class="num">${F(x.reportTheory)}</td><td class="num">${F(x.reportActual)}</td><td><input class="count" data-rm="${x.rm}" type="number" step="any" value="${x.count??''}"></td><td class="num">${x.diff==null?'':F(x.diff)}</td><td class="num">${x.diffp==null?'':F(x.diffp)+'%'}</td><td class="num">${F(x.cost)}</td><td class="num">${F(x.vc)}</td><td class="${x.status==='Short'?'bad':x.status==='Over'?'warn':x.status==='OK'?'ok':''}">${x.status}</td></tr>`).join('');$$('.count').forEach(i=>i.onchange=()=>{const b=$('#branch').value,row=S.analysis.find(x=>x.rm===i.dataset.rm);if(!row)return;if(i.value===''){localStorage.removeItem(countsKey(b,row.rm));row.count=null;row.diff=null;row.diffp=null;row.vc=0;row.status=row.missingConv?'Needs conversion':'Not counted'}else{localStorage.setItem(countsKey(b,row.rm),i.value);row.count=Number(i.value);row.diff=row.calc==null?null:row.count-row.calc;row.diffp=row.diff==null||Math.abs(row.calc)<1e-9?null:row.diff/row.calc*100;row.vc=row.diff==null?0:row.diff*row.cost;row.status=row.missingConv?'Needs conversion':Math.abs(row.diff)<.0005?'OK':row.diff<0?'Short':'Over'}render()})}
render=function(){r0();r1()};
const ec=[['RM',x=>x.rm],['Description',x=>x.desc],['Unit',x=>x.unit],['B/F',x=>x.bf],['GR',x=>x.gr],['T.In',x=>x.tin],['T.Out',x=>x.tout],['WIP Out',x=>x.wipout],['Damage',x=>x.damage],['Waste',x=>x.waste],['BOM Raw Usage',x=>x.bomRaw],['BOM Stock Usage',x=>x.bom??''],['Movement Sales Usage',x=>x.mov],['Usage Var',x=>x.uv??''],['Calc Theory',x=>x.calc??''],['Report Theory',x=>x.reportTheory],['Actual Stock',x=>x.reportActual],['Actual Count',x=>x.count??''],['Count Diff',x=>x.diff??''],['Diff %',x=>x.diffp??''],['Std.Cost',x=>x.cost],['Variance Cost',x=>x.vc],['Status',x=>x.status]];
const er=()=>filteredAnalysis().map(x=>ec.map(([,g])=>g(x)));
downloadCsv=function(){const lines=[ec.map(x=>x[0]).join(',')].concat(er().map(r=>r.map(escCsv).join(','))),el=document.createElement('a');el.href=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}));el.download=exportFileBase()+'.csv';el.click();URL.revokeObjectURL(el.href)};
exportExcelFile=function(){if(!window.XLSX){alert('ตัวสร้าง Excel ยังโหลดไม่สำเร็จ กรุณา Refresh แล้วลองใหม่');return}const m=exportMeta(),rows=er(),aoa=[['KAMU Inventory Stock Checker'],['Branch',m.branch],['Item Sale Date',m.date],['Custom Check',m.custom],['Status',m.status],['Exported Rows',m.rows],[],ec.map(x=>x[0]),...rows],ws=XLSX.utils.aoa_to_sheet(aoa);ws['!freeze']={xSplit:3,ySplit:8};ws['!cols']=ec.map((x,i)=>({wch:i===1?34:i===0?14:i===2?12:16}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Inventory Audit');XLSX.writeFile(wb,exportFileBase()+'.xlsx')};
makeExportPages=function(){const data=filteredAnalysis(),m=exportMeta(),per=20,total=Math.max(1,Math.ceil(data.length/per)),pages=[],cc=[['RM',x=>x.rm],['Description',x=>x.desc],['Unit',x=>x.unit],['B/F',x=>F(x.bf)],['GR',x=>F(x.gr)],['T.In',x=>F(x.tin)],['T.Out',x=>F(x.tout)],['WIP Out',x=>F(x.wipout)],['Damage',x=>F(x.damage)],['Waste',x=>F(x.waste)],['BOM Stock',x=>x.bom==null?'—':F(x.bom)],['Sales Usage',x=>F(x.mov)],['Actual Stock',x=>F(x.reportActual)],['Actual Count',x=>x.count??''],['Count Diff',x=>x.diff==null?'':F(x.diff)],['Diff %',x=>x.diffp==null?'':F(x.diffp)+'%'],['Variance Cost',x=>F(x.vc)],['Status',x=>x.status]];for(let p=0;p<total;p++){const part=data.slice(p*per,(p+1)*per),box=document.createElement('div');box.style.cssText='position:fixed;left:-100000px;top:0;width:1800px;padding:30px;background:#fff;color:#173a28;font-family:Arial,sans-serif;box-sizing:border-box';box.innerHTML=`<div style="display:flex;justify-content:space-between;border-bottom:4px solid #238a55;padding-bottom:15px;margin-bottom:16px"><div><div style="font-size:28px;font-weight:800">KAMU Inventory Stock Checker</div><div style="font-size:16px;margin-top:5px">Inventory Audit Report</div></div><div style="text-align:right;font-size:14px">Page ${p+1}/${total}<br>${new Date().toLocaleString('th-TH')}</div></div><div style="display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:10px;font-size:14px;margin-bottom:16px"><div><b>Branch:</b> ${m.branch}</div><div><b>Date:</b> ${m.date}</div><div><b>Custom:</b> ${m.custom}</div><div><b>Status:</b> ${m.status}</div></div><table style="width:100%;border-collapse:collapse;font-size:9px"><thead><tr>${cc.map(c=>`<th style="background:#dff4e7;border:1px solid #abd5ba;padding:5px;text-align:left">${c[0]}</th>`).join('')}</tr></thead><tbody>${part.map((x,i)=>`<tr style="background:${i%2?'#f8fcf9':'#fff'}">${cc.map(c=>`<td style="border:1px solid #d5e6dc;padding:5px">${String(c[1](x)??'')}</td>`).join('')}</tr>`).join('')}</tbody></table>`;document.body.appendChild(box);pages.push(box)}return pages};
const st=document.createElement('style');st.textContent='.tablewrap table{--rm-col:92px;--desc-col:250px;--unit-col:90px}.tablewrap table th:nth-child(1),.tablewrap table td:nth-child(1){position:sticky;left:0;width:var(--rm-col);min-width:var(--rm-col);max-width:var(--rm-col);z-index:6}.tablewrap table th:nth-child(2),.tablewrap table td:nth-child(2){position:sticky;left:var(--rm-col);width:var(--desc-col);min-width:var(--desc-col);max-width:var(--desc-col);z-index:6}.tablewrap table th:nth-child(3),.tablewrap table td:nth-child(3){position:sticky;left:calc(var(--rm-col) + var(--desc-col));width:var(--unit-col);min-width:var(--unit-col);max-width:var(--unit-col);z-index:6;border-right:2px solid #b8d9c4}.tablewrap table th:nth-child(-n+3){background:#eaf7ef;z-index:9}.tablewrap table td:nth-child(-n+3){background:#fff}@media(max-width:640px){.tablewrap table{--rm-col:78px;--desc-col:170px;--unit-col:72px}}';document.head.appendChild(st);
$('#exportCsv').onclick=downloadCsv;$('#exportExcel').onclick=exportExcelFile;render();
})();
