const json=(v,status=200,extra={})=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json; charset=utf-8',...extra}});
const enc=new TextEncoder(); const digest=async x=>new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(x)));
const hex=b=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');
const bytes=()=>crypto.getRandomValues(new Uint8Array(16));
const b64=b=>btoa(String.fromCharCode(...b)).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
const dec=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
async function passwordHash(password,salt=b64(bytes())){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']); const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:dec(salt),iterations:130000,hash:'SHA-256'},key,256);return salt+'.'+hex(new Uint8Array(bits));}
async function verifyPassword(password,stored){const [salt]=stored.split('.');return await passwordHash(password,salt)===stored;}
async function hmac(secret,message){const k=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(new Uint8Array(await crypto.subtle.sign('HMAC',k,enc.encode(message))));}
async function token(user,env){const payload=b64(enc.encode(JSON.stringify({uid:user.id,exp:Date.now()+1000*60*60*12})));return payload+'.'+await hmac(env.SESSION_SECRET,payload);}
async function current(req,env){const t=(req.headers.get('authorization')||'').replace(/^Bearer /i,'');const [a,b]=t.split('.');if(!a||!b||!env.SESSION_SECRET||await hmac(env.SESSION_SECRET,a)!==b)return null;let data;try{data=JSON.parse(new TextDecoder().decode(dec(a)))}catch{return null}if(Date.now()>data.exp)return null;return await env.DB.prepare('SELECT id,username,role,branch,active FROM users WHERE id=?').bind(data.uid).first().then(x=>x?.active?x:null);}
const isMaster=k=>['bom','wip','itemmaster'].includes(k);
const validKind=k=>['bom','wip','itemmaster','itemsale','stockmovement','stockcount'].includes(k);
const safeUser=u=>({id:u.id,username:u.username,role:u.role,branch:u.branch,active:!!u.active});
const cors=origin=>({'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS','access-control-allow-headers':'content-type,authorization','vary':'Origin'});
const parse=async req=>{const x=await req.json();if(!x||typeof x!=='object'||Array.isArray(x))throw new Error('Invalid JSON object');return x;};
export default {async fetch(req,env){const allowed=env.ALLOWED_ORIGIN||'https://testbitt.github.io',origin=req.headers.get('origin');if(origin&&origin!==allowed)return json({error:'Origin not allowed'},403);const hdr=cors(allowed);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:hdr});
try{
if(!env.DB||!env.SESSION_SECRET||!env.ADMIN_SETUP_PIN)return json({error:'Server configuration incomplete'},503,hdr);
const u=new URL(req.url),path=u.pathname;
if(path==='/health')return json({ok:true,storage:'cloudflare-d1'},200,hdr);
if(path==='/bootstrap'&&req.method==='POST'){
const count=await env.DB.prepare('SELECT COUNT(*) as n FROM users WHERE role=?').bind('admin').first();
if(count.n)return json({error:'Admin already exists'},409,hdr);
const b=await parse(req);if(typeof b.pin!=='string'||b.pin!==env.ADMIN_SETUP_PIN)return json({error:'Incorrect setup PIN'},403,hdr);
if(typeof b.password!=='string'||b.password.length<12)return json({error:'Admin password must be at least 12 characters'},400,hdr);
const uid=crypto.randomUUID();await env.DB.prepare("INSERT INTO users(id,username,password_hash,role,branch) VALUES(?,?,?,'admin','')").bind(uid,String(b.username||'admin').trim(),await passwordHash(b.password)).run();
return json({ok:true},201,hdr);
}
if(path==='/login'&&req.method==='POST'){
const b=await parse(req);const usr=await env.DB.prepare('SELECT * FROM users WHERE username=? AND active=1').bind(String(b.username||'')).first();
if(!usr||!await verifyPassword(String(b.password||''),usr.password_hash))return json({error:'Invalid credentials'},401,hdr);
return json({token:await token(usr,env),user:safeUser(usr)},200,hdr);
}
const me=await current(req,env);if(!me)return json({error:'Unauthorized'},401,hdr);
if(path==='/me'&&req.method==='GET')return json({user:safeUser(me)},200,hdr);
if(path==='/users'&&req.method==='GET'){if(me.role!=='admin')return json({error:'Forbidden'},403,hdr);const all=await env.DB.prepare('SELECT id,username,role,branch,active FROM users ORDER BY username').all();return json({users:all.results.map(safeUser)},200,hdr);}
if(path==='/users'&&req.method==='POST'){if(me.role!=='admin')return json({error:'Forbidden'},403,hdr);const b=await parse(req);if(!b.username||typeof b.password!=='string'||b.password.length<10||!['admin','user'].includes(b.role)||typeof b.branch!=='string')return json({error:'Invalid user fields'},400,hdr);if(b.role==='user'&&!b.branch.trim())return json({error:'Branch required'},400,hdr);const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO users(id,username,password_hash,role,branch) VALUES(?,?,?,?,?)').bind(id,b.username.trim(),await passwordHash(b.password),b.role,b.branch.trim()).run();return json({id},201,hdr);}
if(path.startsWith('/users/')&&req.method==='PUT'){if(me.role!=='admin')return json({error:'Forbidden'},403,hdr);const id=decodeURIComponent(path.split('/')[2]||'');const b=await parse(req);const old=await env.DB.prepare('SELECT * FROM users WHERE id=?').bind(id).first();if(!old)return json({error:'Not found'},404,hdr);const role=b.role||old.role;if(!['admin','user'].includes(role))return json({error:'Invalid role'},400,hdr);const active=b.active===undefined?old.active:Number(!!b.active);if(id===me.id&&(role!=='admin'||!active))return json({error:'Cannot deactivate own admin'},400,hdr);const ph=b.password?await passwordHash(b.password):old.password_hash;if(b.password&&b.password.length<10)return json({error:'Short password'},400,hdr);await env.DB.prepare("UPDATE users SET username=?,password_hash=?,role=?,branch=?,active=?,updated_at=datetime('now') WHERE id=?").bind(b.username||old.username,ph,role,b.branch??old.branch,active,id).run();return json({ok:true},200,hdr);}
if(path==='/datasets'&&req.method==='GET'){const kind=u.searchParams.get('kind');if(kind&&!validKind(kind))return json({error:'Invalid kind'},400,hdr);const sql=me.role==='admin'?'SELECT id,kind,branch,owner_id,row_count,original_file,report_date,updated_at FROM datasets WHERE (? IS NULL OR kind=?) ORDER BY updated_at DESC':'SELECT id,kind,branch,owner_id,row_count,original_file,report_date,updated_at FROM datasets WHERE (? IS NULL OR kind=?) AND (kind IN (\'bom\',\'wip\',\'itemmaster\') OR branch=?) ORDER BY updated_at DESC';const args=me.role==='admin'?[kind,kind]:[kind,kind,me.branch];const rows=await env.DB.prepare(sql).bind(...args).all();return json({datasets:rows.results},200,hdr);}
if(path==='/datasets'&&req.method==='POST'){const b=await parse(req);if(!validKind(b.kind)||!Array.isArray(b.rows)||b.rows.length>25000)return json({error:'Invalid dataset; max 25000 rows'},400,hdr);if(isMaster(b.kind)&&me.role!=='admin')return json({error:'Admin only master data'},403,hdr);const branch=isMaster(b.kind)?'':me.role==='admin'?String(b.branch||''):me.branch;if(!isMaster(b.kind)&&!branch)return json({error:'Branch required'},400,hdr);const raw=JSON.stringify(b.rows);if(raw.length>3e6)return json({error:'Too large; split file'},413,hdr);const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO datasets(id,kind,branch,owner_id,rows_json,row_count,original_file,report_date) VALUES(?,?,?,?,?,?,?,?)').bind(id,b.kind,branch,me.id,raw,b.rows.length,String(b.filename||''),b.reportDate||null).run();await env.DB.prepare('INSERT INTO audit_logs(id,user_id,action,kind,branch,detail) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),me.id,'upload',b.kind,branch,String(b.filename||'')).run();return json({id,rowCount:b.rows.length,branch},201,hdr);}
if(path.startsWith('/datasets/')&&req.method==='GET'){const id=decodeURIComponent(path.split('/')[2]||'');const row=await env.DB.prepare('SELECT * FROM datasets WHERE id=?').bind(id).first();if(!row)return json({error:'Not found'},404,hdr);if(me.role!=='admin'&&!isMaster(row.kind)&&row.branch!==me.branch)return json({error:'Forbidden'},403,hdr);return json({dataset:{id:row.id,kind:row.kind,branch:row.branch,rows:JSON.parse(row.rows_json),rowCount:row.row_count,updatedAt:row.updated_at}},200,hdr);}
if(path.startsWith('/datasets/')&&req.method==='DELETE'){const id=decodeURIComponent(path.split('/')[2]||'');const row=await env.DB.prepare('SELECT * FROM datasets WHERE id=?').bind(id).first();if(!row)return json({error:'Not found'},404,hdr);if(me.role!=='admin'&&(isMaster(row.kind)||row.branch!==me.branch))return json({error:'Forbidden'},403,hdr);await env.DB.prepare('DELETE FROM datasets WHERE id=?').bind(id).run();await env.DB.prepare('INSERT INTO audit_logs(id,user_id,action,kind,branch,detail) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),me.id,'delete',row.kind,row.branch,id).run();return json({ok:true},200,hdr);}
return json({error:'Not found'},404,hdr);
}catch(e){return json({error:e instanceof SyntaxError?'Invalid JSON':'Request failed',detail:String(e.message||'')},400,hdr);}
}};
