const CONFIG={SPREADSHEET_ID:'1vEqeMB2WYka2p64LpV8fvuUuX-MAHHuJlPAydUPuguQ',ATTACHMENT_FOLDER_ID:'1FPw1qdnpcdJiW8f-VnWp4SprTusrtDQ6',TRAVEL_SHEET:'Travel Expense',OT_SHEET:'OT Record',TZ:'Asia/Bangkok'};
function doGet(){return json_({success:true,message:'KAMU Travel & OT API พร้อมใช้งาน',version:'summary-1'});}
function doPost(e){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const p=parsePayload_(e),a=String(p.action||'');if(a==='saveTravelExpense')return saveTravelExpense_(p);if(a==='saveOT')return saveOT_(p);if(a==='getTravelSummary')return getTravelSummary_(p);if(a==='getOTSummary')return getOTSummary_(p);if(a==='ping')return json_({success:true,message:'pong',version:'summary-1'});throw new Error('Unknown action: '+a);}catch(err){return json_({success:false,message:String(err&&err.message||err)});}finally{try{lock.releaseLock();}catch(_){}}}
function authorizeAll(){const ss=SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID),folder=DriveApp.getFolderById(CONFIG.ATTACHMENT_FOLDER_ID);if(!ss.getSheetByName(CONFIG.TRAVEL_SHEET))throw new Error('ไม่พบชีต '+CONFIG.TRAVEL_SHEET);if(!ss.getSheetByName(CONFIG.OT_SHEET))throw new Error('ไม่พบชีต '+CONFIG.OT_SHEET);const f=folder.createFile(Utilities.newBlob('KAMU AUTH '+new Date().toISOString(),'text/plain','KAMU_AUTH_TEST.txt'));f.setTrashed(true);return 'READY | '+ss.getName()+' | '+folder.getName();}
function saveTravelExpense_(p){const sh=sheet_(CONFIG.TRAVEL_SHEET),id='TRV-'+Utilities.formatDate(new Date(),CONFIG.TZ,'yyyyMMdd-HHmmss-SSS'),out=num_(p.distanceOut),back=num_(p.distanceBack),km=round2_(out+back),amount=round2_(num_(p.travelAmount));const outUrl=saveAttachment_(p.receiptOutData,p.receiptOutName,p.receiptOutType,id+'-OUT'),backUrl=saveAttachment_(p.receiptBackData,p.receiptBackName,p.receiptBackType,id+'-BACK');sh.appendRow([new Date(),id,safe_(p.travelDate),safe_(p.origin),safe_(p.destination),safe_(p.employeeId),safe_(p.employeeName),safe_(p.transportType),out,outUrl,back,backUrl,km,amount,'บันทึกแล้ว']);return json_({success:true,message:'บันทึกค่าเดินทางและไฟล์แนบเรียบร้อย',recordId:id,claimId:id,receiptOutUrl:outUrl,receiptBackUrl:backUrl});}
function saveOT_(p){const sh=sheet_(CONFIG.OT_SHEET),id='OT-'+Utilities.formatDate(new Date(),CONFIG.TZ,'yyyyMMdd-HHmmss-SSS');sh.appendRow([new Date(),id,safe_(p.employeeId),safe_(p.employeeName),safe_(p.branch),safe_(p.otDate),safe_(p.startTime),safe_(p.endTime),round2_(num_(p.otHours)),safe_(p.otType),safe_(p.otReason),'บันทึกแล้ว','','']);return json_({success:true,message:'บันทึก OT เรียบร้อย',recordId:id});}
function getTravelSummary_(p){const emp=safe_(p.employeeId);if(!emp)throw new Error('กรุณาระบุรหัสพนักงาน');const sh=sheet_(CONFIG.TRAVEL_SHEET),last=sh.getLastRow();if(last<2)return json_({success:true,employeeName:'',records:[],totals:{count:0,totalKm:0,totalAmount:0}});const rows=sh.getRange(2,1,last-1,15).getValues(),records=[];let name='',km=0,amount=0;rows.forEach(r=>{if(safe_(r[5])!==emp)return;const d=dateKey_(r[2]);if(!matchDate_(d,p))return;name=name||safe_(r[6]);const rec={recordId:safe_(r[1]),date:d,origin:safe_(r[3]),destination:safe_(r[4]),employeeId:safe_(r[5]),employeeName:safe_(r[6]),transportType:safe_(r[7]),distanceOut:num_(r[8]),receiptOutUrl:safe_(r[9]),distanceBack:num_(r[10]),receiptBackUrl:safe_(r[11]),totalKm:num_(r[12]),amount:num_(r[13]),status:safe_(r[14])};km+=rec.totalKm;amount+=rec.amount;records.push(rec);});records.sort((a,b)=>b.date.localeCompare(a.date)||b.recordId.localeCompare(a.recordId));return json_({success:true,employeeName:name,records,totals:{count:records.length,totalKm:round2_(km),totalAmount:round2_(amount)}});}
function getOTSummary_(p){const emp=safe_(p.employeeId);if(!emp)throw new Error('กรุณาระบุรหัสพนักงาน');const sh=sheet_(CONFIG.OT_SHEET),last=sh.getLastRow();if(last<2)return json_({success:true,employeeName:'',records:[],totals:{count:0,totalHours:0}});const rows=sh.getRange(2,1,last-1,14).getValues(),records=[];let name='',hours=0;rows.forEach(r=>{if(safe_(r[2])!==emp)return;const d=dateKey_(r[5]);if(!matchDate_(d,p))return;name=name||safe_(r[3]);const rec={recordId:safe_(r[1]),date:d,employeeId:safe_(r[2]),employeeName:safe_(r[3]),branch:safe_(r[4]),startTime:timeKey_(r[6]),endTime:timeKey_(r[7]),hours:num_(r[8]),otType:safe_(r[9]),reason:safe_(r[10]),status:safe_(r[11])};hours+=rec.hours;records.push(rec);});records.sort((a,b)=>b.date.localeCompare(a.date)||b.recordId.localeCompare(a.recordId));return json_({success:true,employeeName:name,records,totals:{count:records.length,totalHours:round2_(hours)}});}
function matchDate_(d,p){if(!d)return false;const month=safe_(p.month),start=safe_(p.startDate),end=safe_(p.endDate);if(month&&d.slice(0,7)!==month)return false;if(start&&d<start)return false;if(end&&d>end)return false;return true;}
function dateKey_(v){if(v instanceof Date&&!isNaN(v))return Utilities.formatDate(v,CONFIG.TZ,'yyyy-MM-dd');const s=safe_(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(m)return m[3]+'-'+String(m[2]).padStart(2,'0')+'-'+String(m[1]).padStart(2,'0');return s;}
function timeKey_(v){if(v instanceof Date&&!isNaN(v))return Utilities.formatDate(v,CONFIG.TZ,'HH:mm');if(typeof v==='number'&&isFinite(v)){let mins=Math.round((v%1)*1440),h=Math.floor(mins/60)%24,m=mins%60;return String(h).padStart(2,'0')+':'+String(m).padStart(2,'0');}return safe_(v);}
function saveAttachment_(dataUrl,originalName,mimeType,prefix){if(!dataUrl)return '';const m=String(dataUrl).match(/^data:([^;]+);base64,(.+)$/);if(!m)throw new Error('รูปแบบไฟล์แนบไม่ถูกต้อง: '+safe_(originalName));const bytes=Utilities.base64Decode(m[2]);if(bytes.length>4*1024*1024)throw new Error('ไฟล์ '+safe_(originalName)+' เกิน 4 MB');const folder=DriveApp.getFolderById(CONFIG.ATTACHMENT_FOLDER_ID),blob=Utilities.newBlob(bytes,m[1]||mimeType||'application/octet-stream',safeFileName_(prefix+'-'+(originalName||'attachment'))),file=folder.createFile(blob);return file.getUrl();}
function sheet_(name){const sh=SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID).getSheetByName(name);if(!sh)throw new Error('ไม่พบชีต '+name);return sh;}
function parsePayload_(e){try{return JSON.parse(e&&e.postData&&e.postData.contents?e.postData.contents:'{}');}catch(_){throw new Error('JSON payload ไม่ถูกต้อง');}}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
function safe_(v){return v===null||v===undefined?'':String(v).trim();}
function safeFileName_(n){return String(n||'attachment').replace(/[\\/:*?"<>|#%{}~&]/g,'_').replace(/\s+/g,' ').trim();}
function num_(v){const n=Number(v);return Number.isFinite(n)?n:0;}
function round2_(n){return Math.round(Number(n||0)*100)/100;}
