/* Version 3.5 — Admin Full Upload + Cup Usage + Secure User Password Reset */
(()=>{
const ADMIN_DATA_API='https://jbagitudrjpentdneiju.supabase.co/functions/v1/kamu-inventory-admin-data';
const ROLE_KEY='kamuInvCloudRole',TOKEN_KEY='kamuInvCloudToken';
let adminOwnLoaded=false,loadingAdminOwn=false;
function role(){return localStorage.getItem(ROLE_KEY)||''}
function token(){return localStorage.getItem(TOKEN_KEY)||''}
async function adminData(action,data={}){const r=await fetch(ADMIN_DATA_API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token()},body:JSON.stringify({action,...data})});let x={};try{x=await r.json()}catch{}if(!r.ok||x.ok===false)throw Error(x.error||`HTTP ${r.status}`);return x}
function adminDatasetMeta(type,file){if(type==='stock')return{file_name:file.name,rows:S.stock.length,branches:new Set(S.stock.map(r=>T(V(r,'wh'))).filter(Boolean)).size,stock_date:S.stockDate||''};return{file_name:file.name,rows:S.item.length,branches:new Set(S.item.map(r=>T(V(r,'wh'))).filter(Boolean)).size}}
function applyAdminOwn(x){const ds=x?.datasets||{},md=x?.metadata||{};S.stock=Array.isArray(ds.stock)?ds.stock:[];S.item=Array.isArray(ds.item)?ds.item:[];S.stockDate=T(md.stock?.stock_date||md.stock?.stockDate||'');S.meta.stock=T(md.stock?.file_name||md.stock?.name||'');S.meta.item=T(md.item?.file_name||md.item?.name||'');selectedRM.clear();S.analysis=[];S.needs=[];S.recon=[];S.currentExpected=new Map();buildIndexes();refresh();renderCustomChecks();compute();const sel=$('#adminUserSelect');if(sel)sel.value='';adminOwnLoaded=true}
async function loadAdminOwn(force=false){if(role()!=='admin'||loadingAdminOwn||(!force&&adminOwnLoaded))return;loadingAdminOwn=true;try{const x=await adminData('load');applyAdminOwn(x)}catch(e){console.warn('Admin Stock/Item load',e)}finally{loadingAdminOwn=false}}
function showCup(){const c=$('#cupUsageCard');if(c)c.style.display=''}
function renameRegistration(){const b=document.querySelector('.cloud-mode[data-mode="register"]');if(b&&b.textContent!=='ลงทะเบียนเข้าใช้งาน')b.textContent='ลงทะเบียนเข้าใช้งาน';const f=$('#cloudRegisterForm');if(f){const s=f.querySelector('button[type="submit"]');if(s&&s.textContent!=='ลงทะเบียนและเข้าใช้งาน')s.textContent='ลงทะเบียนและเข้าใช้งาน'}}
function hideUploadMeta(){['mStock','mItem','mBom','mConvert'].forEach(id=>{const e=$('#'+id);if(e&&e.style.display!=='none')e.style.display='none'})}
function userIdMap(){const m=new Map(),s=$('#adminUserSelect');if(!s)return m;[...s.options].forEach(o=>{if(o.value)m.set((o.textContent||'').trim(),o.value)});return m}
function passwordResetModal(userId,username){return new Promise(resolve=>{const wrap=document.createElement('div');wrap.className='admin-reset-backdrop';wrap.innerHTML=`<div class="admin-reset-box"><h3>🔐 ตั้งรหัสใหม่</h3><p>User: <b>${String(username).replaceAll('<','&lt;')}</b></p><label>รหัสผ่านใหม่<input type="password" id="resetPass1" autocomplete="new-password"></label><label>ยืนยันรหัสผ่าน<input type="password" id="resetPass2" autocomplete="new-password"></label><div class="admin-reset-error"></div><div class="admin-reset-actions"><button class="btn alt" type="button" data-cancel>ยกเลิก</button><button class="btn" type="button" data-save>ตั้งรหัสใหม่</button></div></div>`;document.body.appendChild(wrap);const p1=wrap.querySelector('#resetPass1'),p2=wrap.querySelector('#resetPass2'),err=wrap.querySelector('.admin-reset-error');const close=v=>{wrap.remove();resolve(v)};wrap.querySelector('[data-cancel]').onclick=()=>close(null);wrap.onclick=e=>{if(e.target===wrap)close(null)};wrap.querySelector('[data-save]').onclick=()=>{const a=p1.value,b=p2.value;if(a.length<4){err.textContent='รหัสผ่านต้องมีอย่างน้อย 4 ตัวอักษร';p1.focus();return}if(a!==b){err.textContent='รหัสผ่านทั้งสองช่องไม่ตรงกัน';p2.focus();return}close(a)};setTimeout(()=>p1.focus(),20)})}
async function resetUserPassword(userId,username){if(!userId)return;const p=await passwordResetModal(userId,username);if(!p)return;try{await adminData('reset_password',{user_id:userId,password:p});alert(`ตั้งรหัสใหม่ให้ ${username} เรียบร้อยแล้ว\nUser ต้อง Login ใหม่ด้วยรหัสที่ตั้งใหม่นี้`)}catch(e){alert('ตั้งรหัสใหม่ไม่สำเร็จ: '+e.message)}}
function decorateAdminUsers(){if(role()!=='admin')return;const body=$('#adminUsersBody'),table=body?.closest('table');if(!body||!table)return;const head=table.querySelector('thead tr');if(head&&!head.querySelector('.admin-password-head')){const th=document.createElement('th');th.className='admin-password-head';th.textContent='Password';head.insertBefore(th,head.children[1]||null)}const ids=userIdMap();[...body.rows].forEach(row=>{if(row.querySelector('.admin-password-cell'))return;const username=(row.cells[0]?.textContent||'').trim(),uid=ids.get(username)||'';const td=document.createElement('td');td.className='admin-password-cell';td.innerHTML=`<span class="password-masked">•••••• <small>เข้ารหัส</small></span> <button class="btn alt small admin-reset-pass" type="button" data-user-id="${uid}" data-username="${username.replaceAll('"','&quot;')}">ตั้งรหัสใหม่</button>`;row.insertBefore(td,row.cells[1]||null)});if(!body.dataset.resetBound){body.dataset.resetBound='1';body.addEventListener('click',e=>{const b=e.target.closest('.admin-reset-pass');if(b)resetUserPassword(b.dataset.userId,b.dataset.username)})}}
function enforceRoleUI(){renameRegistration();hideUploadMeta();const r=role(),cards=$$('#upload .upload-card');if(!r){showCup();return}if(r==='admin'){cards.forEach(c=>{if(c.style.display==='none')c.style.display=''});const rt=$('.tab[data-p="recon"]'),ct=$('.tab[data-p="conversion"]');if(rt)rt.style.display='';if(ct)ct.style.display='';const sel=$('#adminUserSelect');if(sel&&!sel.dataset.v35){sel.dataset.v35='1';sel.addEventListener('change',()=>{adminOwnLoaded=false;if(!sel.value)setTimeout(()=>loadAdminOwn(true),350)})}if(sel&&!sel.value&&!adminOwnLoaded)loadAdminOwn();decorateAdminUsers()}else{cards.forEach((c,i)=>c.style.display=i<2?'':'none');const rt=$('.tab[data-p="recon"]'),ct=$('.tab[data-p="conversion"]');if(rt)rt.style.display='none';if(ct)ct.style.display='none'}showCup();const v=document.querySelector('.version');if(v)v.textContent='Version 3.5 • Public Multi‑User'}
const css=document.createElement('style');css.textContent=`#mStock,#mItem,#mBom,#mConvert{display:none!important}.admin-password-cell{min-width:210px}.password-masked{display:inline-flex;align-items:center;gap:4px;color:#315e46;font-weight:800;margin-right:6px}.password-masked small{font-size:9px;color:#658071;font-weight:700}.admin-reset-backdrop{position:fixed;inset:0;z-index:13000;background:rgba(15,45,29,.42);display:grid;place-items:center;padding:18px}.admin-reset-box{width:min(390px,94vw);background:#fff;border:1px solid #cfe6d7;border-radius:22px;padding:20px;box-shadow:0 20px 60px rgba(17,76,45,.28)}.admin-reset-box h3{margin:0 0 6px}.admin-reset-box p{margin:0 0 14px;color:#658071}.admin-reset-box label{display:block;font-size:11px;font-weight:800;color:#466b55;margin-top:9px}.admin-reset-box input{width:100%;font-size:16px;padding:11px 12px;border:1px solid #bfdcc9;border-radius:12px;margin-top:4px}.admin-reset-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.admin-reset-error{min-height:20px;color:#b42318;font-size:12px;font-weight:700;margin-top:7px}@media(max-width:640px){.admin-reset-actions .btn{flex:1}.admin-password-cell{min-width:180px}}`;document.head.appendChild(css);
const readV30=read;
read=async function(file,type){
 if(role()!=='admin'||!['stock','item'].includes(type))return readV30(file,type);
 if(!file)throw Error('ไม่พบไฟล์');if(!window.XLSX)throw Error('ตัวอ่าน Excel ยังโหลดไม่สำเร็จ กรุณา Refresh แล้วลองใหม่');
 const el=type==='stock'?$('#mStock'):$('#mItem');
 try{
  const current=await adminData('load');
  if(type==='stock'){S.item=Array.isArray(current?.datasets?.item)?current.datasets.item:[];S.meta.item=T(current?.metadata?.item?.file_name||'')}
  else{S.stock=Array.isArray(current?.datasets?.stock)?current.datasets.stock:[];S.stockDate=T(current?.metadata?.stock?.stock_date||'');S.meta.stock=T(current?.metadata?.stock?.file_name||'')}
  const b=await file.arrayBuffer(),wb=XLSX.read(b,{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]];
  if(type==='stock'){const parsed=rows(ws,'stock');if(!parsed.length)throw Error('ไม่พบข้อมูล Stock Movement หลังหัวตาราง');S.stock=parsed;S.stockDate=reportDate(wb,ws);S.meta.stock=file.name}
  else{const parsed=rows(ws,'item');if(!parsed.length)throw Error('ไม่พบข้อมูล Item Sale หลังหัวตาราง');S.item=parsed;S.meta.item=file.name}
  buildIndexes();await save();refresh();compute();await adminData('save',{dataset_type:type,payload:type==='stock'?S.stock:S.item,metadata:adminDatasetMeta(type,file)});adminOwnLoaded=true;const sel=$('#adminUserSelect');if(sel)sel.value='';showCup();
 }catch(e){throw e}
}
const renderV30=render;render=function(){renderV30();showCup()};
function applyAfterAuth(){setTimeout(enforceRoleUI,80);setTimeout(enforceRoleUI,450);setTimeout(enforceRoleUI,1200)}
document.addEventListener('submit',e=>{const id=e.target?.id;if(id==='cloudLoginForm'||id==='cloudRegisterForm'||id==='cloudAdminForm')applyAfterAuth()},true);
setTimeout(enforceRoleUI,100);setTimeout(enforceRoleUI,600);
})();

/* Load clean auth layout v35 */
(()=>{if(document.querySelector('script[data-v35-auth]'))return;const s=document.createElement('script');s.src='https://testbitt.github.io/kamu-inventory-assets/v27/patch27.js?v=35';s.dataset.v35Auth='1';s.async=false;document.head.appendChild(s)})();
